# Generated by Django 5.2.11 on 2026-02-24 22:34

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fobi", "0016_alter_formelement_id_alter_formelemententry_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormEntryProxy",
            fields=[],
            options={
                "verbose_name": "Forms (builder)",
                "verbose_name_plural": "Forms (builder)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fobi.formentry",),
        ),
    ]
